import { v4 as uuid } from "uuid";

export const videosdata = [
  {
    video: "./videos/v1.mp4",
    desc: "7 CrazyClown Comedy That Got Everybody Laughing",
    tag: "comedy",
    playId: uuid(),
    userProfile: "./asset/Kingrashy12.jpg",
    name: "Rapheal C",
    username: "Kingrashy12",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v2.mp4",
    desc: "🤗 She sings nice, she said dj khaled",
    tag: "music",
    playId: uuid(),
    name: "King",
    username: "cr2",
    userProfile: "./asset/huracan sto.jpg",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v3.mp4",
    desc: "How to upload image to cloudinary from backend nodejs",
    tag: "coding",
    playId: uuid(),
    username: "rdev",
    userProfile: "./asset/astrospace",
    name: "King",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v4.mp4",
    desc: "Time travel to the future",
    tag: "comedy",
    playId: uuid(),
    username: "rashyking12",
    userProfile: "./asset/amg-gt-s.jpg",
    name: "funny",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v5.mp4",
    desc: "The 2023 Mercedes-AMG GT63 S Doesn’t Need Your Approval to Rock (POV Drive Revie",
    tag: "cars",
    playId: uuid(),
    userProfile: "./asset/amg-gt-s.jpg",
    name: "Autos",
    username: "autoshop",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v6.mp4",
    desc: "Osj join witch (part 1-4)",
    playId: uuid(),
    tag: "comedy",
    username: "rashyking12",
    userProfile: "./asset/amg-gt-s.jpg",
    name: "funny man",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v7.mp4",
    desc: "Deploy node and express JS project to Vercel _ Hu Nan",
    tag: "coding",
    playId: uuid(),
    userProfile: "./asset/Kingrashy12jpg",
    name: "Rapheal C",
    username: "Kingrashy12",
    gender: "male",
    likes: [],
    comments: [],
  },
  {
    video: "./videos/v8.mp4",
    desc: "KS React🤣 E82 Ft•__Shank Comics_Nasty Blaq_BrainJotter_Funny Bros_Oluwadolarz_L",
    tag: "comedy",
    playId: uuid(),
    userProfile: "./asset/Kingrashy12.jpg",
    name: "Rapheal C",
    username: "Kingrashy12",
    gender: "male",
    likes: [],
    comments: [],
  },
];
